home/urls.py
from django.urls import path
from .views import Index

app_name = 'home'

urlpatterns = [
    path ('', Index.as_view(), name='home')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path("accounts/", include("allauth.urls")),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('recipes/', include('recipes.urls'))
]

templates/includes/footer.html
{% load static %}
<footer class="bg-body-tertiary text-center">
    <div class="container p-2">
        <!-- Social Media Icons -->
        <div>
            <a class="btn text-white btn-floating m-1" href="https://www.facebook.com/" target="_blank">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a class="btn text-white btn-floating m-1" href="https://twitter.com/" target="_blank">
                <i class="fab fa-x-twitter"></i>
            </a>
            <a class="btn text-white btn-floating m-1" href="https://www.instagram.com/" target="_blank">
                <i class="fab fa-instagram"></i>
            </a>
        </div>
    </div>
    <div class="text-center p-1">
        <p class="text-center uppercase special-text">&copy; Copyright 2023
            <a href="https://github.com/rachbry" class="special-text" target="_blank">Rachbry</a>
        </p>
    </div>
</footer>

templates/includes/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark">
    <!-- logo -->
    <a class="navbar-brand mr-auto" href="{% url 'home:home' %}">
        <img src="{% static 'images/recipMe-cropped.png' %}" class="nav-logo" alt="recipeMe logo link to home">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Nav items -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mb-2 mb-lg-0 uppercase">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link {% if request.resolver_match.url_name == 'my_recipes' %}active{% endif %}"
                    aria-current="page" href="{% url 'home:home' %}">My Recipes</a>
                {% else %}
                <a class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page"
                    href="{% url 'home:home' %}">Home</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'recipes' %}active{% endif %}"
                    href="{% url 'recipes' %}">Recipmes</a>
            </li>
            <!-- login or out -->
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'add_recipe' %}active{% endif %}"
                    href="{% url 'add_recipe' %}">Add<i class="fa-solid fa-plus"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page"
                    href="{% url 'account_logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page"
                    href="{% url 'account_signup' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page"
                    href="{% url 'account_login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
        <!-- Search bar -->
        <form class="form-inline my-2 my-lg-0 d-flex flex-sm-row flex-column" role="search" method="GET"
            action="{% url 'search_results' %}">
            <div class="input-group">
                <input class="form-control form-control-sm mr-sm-2" name="q" type="search" placeholder="Search"
                    aria-label="Search">
                <div class="input-group-append">
                    <button class="btn button-action ms-2 ms-sm-0" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>
</nav>